config/routes.rb
Watsticks::Application.routes.draw do
  resources :jobs do
    resources :interviews
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root "welcome#index"
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get 'interviews/user_interviews/:user_id', to: 'interviews#user_interviews', as: :user_interviews

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :signed_in_user

  def new
    @interview = Interview.new
  end

  def index
    @interviews = Interview.where("user_id = user_id AND scheduled_on >= scheduled_on",
     user_id: current_user.id, scheduled_on: Date.today)
  end

  def create
    interview_time = DateTime.strptime(interview_params[:scheduled_on], '%m/%d/%Y %l:%M %p')
    @interview = Interview.new(user_id: current_user.id, scheduled_on: interview_time, job_id: params[:job_id])
    @user = current_user
    if @interview.save
      flash[:success] = 'interview saved!'
      redirect_to @interview.job
    else
      flash[:alert]
    end
  end

  def show
    @interview = Interview.find(params[:id])
  end

  def user_interviews
    @interviews = Interview.where(user_id: params[:user_id]).to_a
    render 'index'
  end

  private

    def interview_params
      params.require(:interview).permit(:scheduled_on, :user_id, :job_id)
    end
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/views/interviews/_interview_details.html.haml
%p
  %strong
    Main Contact:
  Replace me with something meaningful
%p
  %strong
    Date:
  = @job.interviews.first.interview_date
%p
  %strong
    Time:
  = @job.interviews.first.interview_time

app/views/interviews/_interview_form.html.haml
= f.label :date, "Date/Time:"
%div.row
  %div.form-group
    %div.input-group.date#interview_scheduled_on
      = f.datetime_field :scheduled_on, class: "form-control"
      %span{ class: "input-group-addon" }
        %span{ class: "glyphicon glyphicon-calendar" }
          :javascript
            $(function () {
              $('#interview_scheduled_on').datetimepicker();
            });

app/views/interviews/index.html.haml
- provide(:title, 'INTERVIEWS')
%h1 INTERVIEWS
%div.panel.panel-default
  %div.panel-heading
    Here are your upcoming interviews:
    %table.table
      %th
        Company
      %th
        Main Contact
      %th
        Date
      - @interviews.each do |i|
        %tr
          %td.company
            = i.job.company
          %td.contact
          %td.date
            = i.scheduled_on


app/views/interviews/new.html.erb
<h1>Enter interview details</h1>
<div class="row">
  <div class="form-group">
    <%= form_for :interview, url: job_interviews_path do |f| %>
      <%= render 'interview_form', f: f %>
      <%= f.submit "Save interview", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/interviews/show.html.haml
%p
  %strong
    Company:
  = @interview.job.company
%p
  %strong
    Main Contact:
  Replace me with something meaningful
%p
  %strong
    Date:
  = @interview.interview_date
%p
  %strong
    Time:
  = @interview.interview_time
%div.delete_interview
  = link_to "Delete interview", job_interview_path(@interview), method: :delete, class: "btn btn-large btn-danger"