config/routes.rb
Watsticks::Application.routes.draw do
  resources :jobs do
    resources :interviews
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root "welcome#index"
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get 'interviews/user_interviews/:user_id', to: 'interviews#user_interviews', as: :user_interviews

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many :interviews, dependent: :destroy

  default_scope -> { order('created_at DESC') }

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 48 }
  validates :company, presence: true, length: { maximum: 48 }
  validates :industry, presence: true
  validates :date_applied, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :signed_in_user

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.build(job_params)
    if @job.save
      flash[:success] = "job saved"
      redirect_to @job
    else
      render 'new'
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:successj] = "job updated"
      redirect_to @job
    else
      render 'edit'
    end
  end

  def show
    @job = Job.find(params[:id])
    @contact = Contact.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.where(user_id: current_user.id)
  end

  def update_consideration
    @job = Job.find(params[:id])
    @job.update_attributes(:in_consideration, params[:in_consideration])
  end

  def destroy
    Job.find(params[:id]).destroy
    flash[:success] = "Job deleted"
    redirect_to jobs_path
  end

  private
    def job_params
      params.require(:job).permit(:title, :company, :industry, :date_applied, :in_consideration)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def industry_options
    INDUSTRIES
  end
  INDUSTRIES=[
    "Farming and Ranching",
    "Fishing, Hunting and Forestry and Logging",
    "Mining and Quarrying",
    "Agriculture & Mining",
    "Business Services",
    "Accounting and Tax Preparation",
    "Advertising, Marketing and PR",
    "Data and Records Management",
    "Facilities Management and Maintenance",
    "HR and Recruiting Services",
    "Legal Services",
    "Management Consulting",
    "Payroll Services",
    "Sales Services",
    "Security Services",
    "Business Services",
    "Computer and Electronics",
    "Audio, Video and Photography",
    "Computers, Parts and Repair",
    "Consumer Electronics, Parts and Repair",
    "IT and Network Services and Support",
    "Instruments and Controls",
    "Network Security Products",
    "Networking equipment and Systems",
    "Office Machinery and Equipment",
    "Peripherals Manufacturing",
    "Semiconductor and Microchip Manufacturing",
    "Computer and Electronics",
    "Consumer Services",
    "Automotive Repair and Maintenance",
    "Funeral Homes and Services",
    "Laundry and Dry Cleaning",
    "Parking Lots and Garage Management",
    "Personal Care",
    "Photofinishing Services",
    "Consumer Services",
    "Education",
    "Colleges and Universities",
    "Elementary and Secondary Schools",
    "Libraries, Archives and Museums",
    "Sports, Arts, and Recreation Instruction",
    "Technical and Trade Schools",
    "Test Preparation",
    "Education",
    "Energy and Utilities",
    "Alternative Energy Sources",
    "Gas and Electric Utilities",
    "Gasoline and Oil Refineries",
    "Sewage Treatment Facilities",
    "Waste Management and Recycling",
    "Water Treatment and Utilities",
    "Energy and Utilities",
    "Financial Services",
    "Banking",
    "Credit Cards and Related Services",
    "Credit Unions",
    "Insurance and Risk Management",
    "Investment Banking and Venture Capital",
    "Lending and Mortgage",
    "Personal Financial Planning and Private Banking",
    "Securities Agents and Brokers",
    "Trust, Fiduciary, and Custody Activities",
    "Financial Services Other",
    "Government",
    "International Bodies and Organizations",
    "Local Government",
    "National Government",
    "State/Provincial Government",
    "Government Other",
    "Health, Pharmaceuticals, and Biotech",
    "Biotechnology",
    "Diagnostic Laboratories",
    "Doctors and Health Care Practitioners",
    "Hospitals",
    "Medical Devices",
    "Medical Supplies and Equipment",
    "Outpatient Care Centers",
    "Personal Health Care Products",
    "Pharmaceuticals",
    "Residential and Long-term Care Facilities",
    "Veterinary Clinics and Services",
    "Health, Pharmaceuticals, and Biotech Other",
    "Manufacturing",
    "Aerospace and Defense",
    "Alcoholic Beverages",
    "Automobiles, Boats and Motor Vehicles",
    "Chemicals and Petrochemicals",
    "Concrete, Glass and Building Materials",
    "Farming and Mining Machinery and Equipment",
    "Food and Dairy Product Manufacturing and Packaging",
    "Furniture Manufacturing",
    "Metals Manufacturing",
    "Nonalcoholic Beverages",
    "Paper and Paper Products",
    "Plastics and Rubber Manufacturing",
    "Textiles, Apparel and Accessories",
    "Tools, Hardware and Light Machinery",
    "Manufacturing",
    "Media and Entertainment",
    "Adult Entertainment",
    "Motion Picture Exhibitors",
    "Motion Picture and Recording Producers",
    "Newspapers, Books, and Periodicals",
    "Performing Arts",
    "Radio, Television Broadcasting",
    "Media and Entertainment",
    "Non-profit",
    "Advocacy Organizations",
    "Charitable Organizations and Foundations",
    "Professional Associations",
    "Religious Organizations",
    "Social and Membership Organizations",
    "Trade Groups and Labor Unions",
    "Non-profit",
    "Real Estate and Construction",
    "Architecture, Engineering and Design",
    "Construction Equipment and Supplies",
    "Construction and Remodeling",
    "Property Leasing and Management",
    "Real Estate Agents and Appraisers",
    "Real Estate Investment and Development",
    "Real Estate and Construction",
    "Retail",
    "Automobile Dealers",
    "Automobile Parts and Supplies",
    "Beer, Wine and Liquor Stores",
    "Clothing and Shoe Stores",
    "Department Stores",
    "Florist",
    "Furniture Stores",
    "Grocery and Specialty Stores",
    "Hardware and Building Material Dealers",
    "Jewelry, Luggage, and Leather Goods",
    "Office Supplies Stores",
    "Restaurants and Bars",
    "Sporting Goods, Hobby, Books and Music Stores",
    "Retail Others",
    "Software and Internet",
    "Data Analytics, Management, and Internet",
    "E-Commerce and Internet Business",
    "Games and Gaming",
    "Software",
    "Software and Internet",
    "Telecommunications",
    "Cable and Television Providers",
    "Telecommunications Equipment and Accessories",
    "Telephone Service Providers and Carriers",
    "Video and Teleconferencing",
    "Wireless and Mobile",
    "Telecommunications",
    "Transportation and Storage",
    "Air Couriers and Caro Services",
    "Airport, Harbor, and Terminal Operations",
    "Freight Hauling (Rail and Truck)",
    "Marine and Inland Shipping",
    "Moving Companies and Services",
    "Postal, Express Delivery and Couriers",
    "Warehousing and Storage",
    "Transportation and Storage",
    "Travel Recreation and Leisure",
    "Amusement Parks and Attractions",
    "Cruise Ship Operations",
    "Gambling and Gaming Lodging",
    "Participatory Sports and Recreation",
    "Passenger Airlines",
    "Rental Cars",
    "Resorts and Casinos",
    "Spectator Sports and Teams",
    "Taxi, Buses and Transit Systems",
    "Travel Agents and Services",
    "Travel, Recreations and Leisure",
    "Wholesale and Distribution",
    "Apparel Wholesalers",
    "Automobile Parts Wholesalers",
    "Beer, Wine and Liquor Wholesalers",
    "Chemicals and Plastics Wholesalers",
    "Grocery and Food Wholesalers",
    "Lumber and Construction Materials Wholesalers",
    "Metal and Mineral Wholesalers",
    "Office Equipment and Suppliers Wholesalers",
    "Petroleum Products Wholesalers",
    "Wholesale and Distribution"
  ]
end

app/views/jobs/_interview_details.html.haml
%p
  %strong
    Date:
  = @job.interviews.first.interview_date
%p
  %strong
    Time:
  = @job.interviews.first.interview_time
%p
  %strong
    Main Contact:
  Replace me with something meaningful

app/views/jobs/_job_form.html.haml
= render 'shared/job_error_messages'

= f.label :title
= f.text_field :title, placeholder: "Enter Title"

= f.label :company
= f.text_field :company, placeholder: "Enter Company"

= f.label :industry
= f.select :industry, options_for_select(industry_options.sort)

= f.label :date_applied, "Date Applied"
= f.date_field :date_applied

= f.label :in_consideration
= f.radio_button :in_consideration, true
= f.label :no_longer_in_consideration
= f.radio_button :in_consideration, false

app/views/jobs/edit.html.haml
%h1 Edit Job
.row
  .form-group
    = form_for :job, url: job_path, method: :patch do |f|
      = render 'job_form', f: f
      = f.submit "Update job", class: "btn btn-large btn-primary"

app/views/jobs/index.html.erb
<% provide(:title, 'JOBS') %>
<h1>JOBS</h1>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Here is a listing of the jobs you have applied for:</div>

  <!-- Table -->
  <table class="table">
    <th>Title</th>
    <th>Company</th>
    <th>Industry</th>
    <th>Date Applied</th>
    <% @jobs.each do |j| %>
      <tr class="clickable_job_row" data-url="<%=job_path(j)%>">
        <td class="title"><%= j.title %></td>
        <td class="company"><%= j.company %></td>
        <td class="industry"><%= j.industry %></td>
        <td class="date_applied"><%= j.date_applied.strftime('%b %d') %></td>
      </tr>
    <% end %><br>
  </table>
</div>
<div>
  <%= link_to "Add Job", new_job_path, class: "btn btn-large btn-primary" %>
</div>

app/views/jobs/new.html.erb
<h1>Enter job details</h1>
<div class="row">
  <div class="form-group">
    <%= form_for :job, url: jobs_path do |f| %>
      <%= render 'job_form', f: f %>
      <%= f.submit "Save job", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.haml
%p
  %strong
    Job Title:
  = @job.title
%p
  %strong
    Company:
  = @job.company
%p
  %strong
    Industry:
  = @job.industry
%p
  %strong
    Date Applied:
  = @job.date_applied
%p
  %strong
    Still in Consideration:
  = @job.in_consideration
%div.delete_job
  = link_to "Delete job", job_path(@job), method: :delete, class: "btn btn-large btn-danger"
%div.add_interview
  = link_to "Add interview", new_job_interview_path(@job) #class: "btn btn-large btn-default"
%h3 Interviews:
.content
  - if @job.interviews.count > 0
    = render partial: 'interview_details'