config/routes.rb
Watsticks::Application.routes.draw do
  resources :jobs do
    resources :interviews
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root "welcome#index"
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get 'interviews/user_interviews/:user_id', to: 'interviews#user_interviews', as: :user_interviews

end

app/views/layouts/_dash_panel.html.erb
<div class="panel panel-default left-panel">
  <div class="panel-heading">
  </div>
  <div class="panel-body">
    Basic panel example
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Neil West
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Watsticks", root_url, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home",    '/' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">
                Account <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu" data-no-turbolink>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Jobs",    jobs_path %></li>
                <li><%= link_to "Interviews", user_interviews_path(current_user.id) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert #{bootstrap_class_for(key.to_sym)}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>